# Generated by Django 5.1.1 on 2024-09-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_and_chapters', '0007_chapter_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='created_at',
        ),
        migrations.AddField(
            model_name='chapter',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
