# Generated by Django 5.1.1 on 2024-09-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_and_chapters', '0009_book_genre_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
